[build-system]
requires = ["setuptools>=61.0.0,<68.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "materialxmaterials"
version = "1.39.5"
authors = [
  { name="Bernard Kwok", email="kwokcb@gmail.com" },
]
description = "Utilities to obtains materials from material libraries. Supported libraries include PhysicallyBased, GPUOpen, AmbientCG, and PolyHaven."
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "materialx>=1.39.4",
    "requests",
    "pillow"
]

[project.scripts]
materialxMaterials = "materialxMaterials.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]
[tool.setuptools.package-data]
"materialxMaterials.data" = ["**/*"]

[project.urls]
"Homepage" = "https://kwokcb.github.io/materialxMaterials/"
"Issues" = "https://github.com/kwokcb/materialxMaterials/issues"
"Source Code" = "https://github.com/kwokcb/materialxMaterials"
"Documentation" = "https://kwokcb.github.io/materialxMaterials/"

